### PR TITLE
ServiceInstance task status

### PR DESCRIPTION
**Pull request by slemrmartin**
**Issue** https://github.com/RedHatInsights/topological_inventory-ansible_tower/issues/83

Added normalized Task status from Job status to `ServiceInstance.extra["task_status"]`
To avoid provider-specific code in https://github.com/RedHatInsights/topological_inventory-core/pull/187

### CODE REVIEW

**Comment by slemrmartin** [comment]
Hm, I don't understand why it's there previously merged commit (maybe I made an interactive rebase and didn't do _something_). 
But it doesn't matter

**Comment by slemrmartin** [comment]
specs fixed by https://github.com/RedHatInsights/topological_inventory-ansible_tower/pull/86

**Comment by agrare** [comment]
Hey @slemrmartin there are some conflicts on this PR

**Comment by slemrmartin** [comment]
@agrare I rebased it and everything is gone. But it seems the code was merged by #84

**Comment by agrare** [comment]
Okay so it's safe to merge https://github.com/RedHatInsights/topological_inventory-core/pull/187 now then?

**Comment by slemrmartin** [comment]
@agrare yes (https://github.com/RedHatInsights/topological_inventory-core/pull/188). The `task_status` is collected

**Pull request closed without merging**
