### PR TITLE
Status, Started, Finished to ServiceInstance

### PR DESCRIPTION
**Pull request by slemrmartin**
TPINVTRY-726

Status, Started and Finished are added to `extra` (source-type specific data)

### CODE REVIEW

**Comment by agrare** [comment]
@slemrmartin could we set these on the task as part of the operation instead of the service_instance?  It makes more sense for a task to have e.g. started/finished than a service_instance for other platforms (e.g. an OrchestrationStack wouldn't have a "finished" time) and I don't want catalog to depend on checking for something in `#extra` if they don't have to.

**Comment by slemrmartin** [comment]
@agrare I can, but @gmcculloug wanted it in `service_instance`

**Comment by agrare** [comment]
Oh?  @gmcculloug I thought we discussed that checking the task made more sense

**Comment by slemrmartin** [comment]
It's defined in Jira task. So if you have discussed it, I'll change it

**Comment by gmcculloug** [comment]
@agrare Correct, we did and I was ok with that.  Looks like the Jira issue was not updated.

My question is, if the service_instance is representing the Job in Tower does it belong there?  (Maybe in addition to the task?)

**Comment by agrare** [comment]
I'm okay with in addition to, but I don't want you to rely on it in service_instance if we wouldn't be able to set that for any other source-type

**Comment by gmcculloug** [comment]
@agrare I was thinking about how you would view these in the future and seems like data that would be included, but I was only thinking about service_instances representing Tower Jobs.  I can see how that would not work for other providers.

My suggestion would be to do whatever you feel makes the most sense for now.  Thinking that is task and we can revisit service_instance later.

**Comment by agrare** [comment]
Oh this is just for display?

**Comment by gmcculloug** [comment]
Yes, for Catalog order UI.

**Comment by agrare** [comment]
Okay, my bad thought you were using this for waiting for it to finish

**Review by agrare — APPROVED** [review]

**Pull request merged**
