### PR TITLE
Fixed entity_types arr to sweep_inventory

### PR DESCRIPTION
**Pull request by slemrmartin**
There was usually empty list of entity types sent to sweep_inventory as sweep_scope, this PR fixes it

### CODE REVIEW

**Comment by slemrmartin** [comment]
@Ladas pls :eyes:

**Comment by slemrmartin** [comment]
@miq-bot assign @Ladas 
(testing miq-bot :)

**Comment by slemrmartin** [comment]
@miq-bot add-label bug

**Review by Ladas — APPROVED** [review]
:+1:

**Pull request merged**
